import Head from "next/head";
import "./globals.css";
import "./responsive.css";

export const metadata = {
title: "The Fusion Journey",
description: "Generated by The Fusion Journey",
};

const RootLayout = ({ children }) => {


  return (
    <html lang="en">
      <Head>
        <link rel="preload" href="https://d18ftjc6wexpf2.cloudfront.net/fusion-animations/Hero_scroll_animation/Homepage_animation_01.png" as="image"/>
        <link rel="preload" href="https://d18ftjc6wexpf2.cloudfront.net/fusion-animations/videos/homevideo1.mov" as="video"/>
        <link rel="preload" href="https://d18ftjc6wexpf2.cloudfront.net/fusion-animations/videos/homevideo1.mov" as="video"/>
        <link rel="preload" href="https://d18ftjc6wexpf2.cloudfront.net/fusion-animations/videos/homevideo1.webm" as="video"/>
        <link rel="preload" href="/assets/images/json/logo.json" as="json"/>
        <link rel="preload" href="/assets/images/json/Logo_color_palette.json" as="json"/>
        <link rel="preload" href="/assets/images/json/Logo_pin.json" as="json"/>
        <link rel="preload" href="/assets/images/json/Logo_puzzle.json" as="json"/>
        <link rel="preload" href="/assets/images/json/Logo_trees.json" as="json"/>
        <link rel="preload" href="/assets/images/json/Logo_yin_yang.json" as="json"/>
        <link
          rel="preload"
          href="/assets/fonts/GT-sectra-fine-book.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/assets/fonts/GT-sectra-fine-book.woff"
          as="font"
          type="font/woff"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/assets/fonts/GT-sectra-fine-book.ttf"
          as="font"
          type="font/truetype"
          crossOrigin="anonymous"
        />
      </Head>
      {children}
    </html>
  );
}


export default RootLayout;
